language: node_js
node_js:
  - "6"
  - "8"
  - "10"
dist: trusty
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt-get update
  - sudo apt-get install mono-complete
install:
  - npm install
script:
  - npm test
